# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='secret_identity',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
